"""LatticeStore protocol definition — storage abstraction."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from lattice_lens.models import Fact


@runtime_checkable
class LatticeStore(Protocol):
    """Storage abstraction. All CLI/MCP tools program against this."""

    def get(self, code: str) -> Fact | None: ...
    def list_facts(self, **filters) -> list[Fact]: ...
    def create(self, fact: Fact) -> Fact: ...
    def update(self, code: str, changes: dict, reason: str) -> Fact: ...
    def deprecate(self, code: str, reason: str) -> Fact: ...
    def exists(self, code: str) -> bool: ...
    def all_codes(self) -> list[str]: ...
    def stats(self) -> dict: ...
